#!/usr/bin/env python3
"""Deploy ATTAR canvases generated by generate_rooms_attar.py.
This copies the newly generated attar-base canvases into the main room-canvas
directory, overwriting existing base images for a refined luxury look."""
import shutil, os

SRC = os.path.join(os.path.dirname(__file__), 'tmp_attar')
DST = os.path.join(os.path.dirname(__file__), '../room-canvas')

MAPPING = {
    'storefront-attar-base.webp': 'storefront-base.webp',
    'lounge-attar-base.webp': 'lounge-base.webp',
    'designer_houses-attar-base.webp': 'designer-houses-base.webp',
    'occasions-attar-base.webp': 'occasions-base.webp',
    'featured_collections-attar-base.webp': 'featured-collections-base.webp',
}

def main():
    os.makedirs(DST, exist_ok=True)
    for src_name, dst_name in MAPPING.items():
        src_path = os.path.join(SRC, src_name)
        dst_path = os.path.join(DST, dst_name)
        if os.path.exists(src_path):
            print(f"Deploying {src_name} -> {dst_name}")
            shutil.copyfile(src_path, dst_path)
        else:
            print(f"WARN: {src_name} not found in {SRC}")
    print("Deployment complete.")

if __name__ == '__main__':
    main()
